# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'
# TODO: 引入 tasks
require 'resque/tasks'

# TODO: rails 5.x 加入
task 'resque:setup' => :environment

Rails.application.load_tasks
