---
chdir: "/Users/vincent/project/ruby-self-training-demos/web-server-thin-demo"
environment: development
address: 0.0.0.0
port: 3000
timeout: 30
log: "/Users/vincent/project/ruby-self-training-demos/web-server-thin-demo/log/thin.log"
pid: "/Users/vincent/project/ruby-self-training-demos/web-server-thin-demo/pids/thin.pid"
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
daemonize: true
